### PR TITLE
Website update 2 + README.md update + Pizza Parlor Music update 2

### PR DESCRIPTION
**Pull request by P-AS**
pizza parlor music was bothering me

### CODE REVIEW

**Comment by PandaSRC** [comment]
also you should give me the dev role back that would be funny

**Comment by PandaSRC** [comment]
Its in a better state now I think it can be merged

**Comment by sticks-stuff** [comment]
not sure if i agree with changing the music, im pretty sure it was decided that we should leave all game files vanilla (where reasonable) and leave changing files up to the user

**Comment by PandaSRC** [comment]
the ones we have are already changed https://github.com/sticks-stuff/CPSC/pull/64

**Comment by sticks-stuff** [comment]
That is true, now I feel like reverting that because it makes more sense to me to leave all files vanilla and let the user change what they want. Maybe we could include an HD Audio mod in the mods folder, similar to how we include the 30 fps mod?

**Pull request closed without merging**
